// Mocks generated by Mockito 5.2.0 from annotations
// in reemper/test/presenters/modalities_presenter_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:reemper/models/modality_model.dart' as _i3;
import 'package:reemper/usecases/get_modalities_use_case.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [GetModalitiesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetModalitiesUseCase extends _i1.Mock
    implements _i2.GetModalitiesUseCase {
  MockGetModalitiesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.ModalityModel> invoke() =>
      (super.noSuchMethod(Invocation.method(#invoke, []),
          returnValue: <_i3.ModalityModel>[]) as List<_i3.ModalityModel>);
}
